name: "SolarConnect"
description: "Addon to integrate your Sunsynk Connect account into Home Assistant"
version: "1.3.2"
slug: "solar_connect"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
options:
  mqtt_broker: "127.0.0.1"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  sunsynk_username: ""
  sunsynk_password: ""
  sunsynk_inverter_serial: ""
  enable_https: false
  refresh_time: 300
schema:
  mqtt_broker: "str"
  mqtt_port: "int"
  mqtt_username: "str"
  mqtt_password: "password"
  sunsynk_username: "str"
  sunsynk_password: "password"
  sunsynk_inverter_serial: "str"
  enable_https: "bool"
  refresh_time: "int"
